# kubectl create -n q6 configmap message-config --from-file=./config.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: message-config
  namespace: q6
data:
  config.json: |
    {
      "message": "良いお年を!!!"
    }
