apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
  namespace: q2
  labels:
    app: http-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: http-server
        image: hatappi/k8s-training:v1.0
        args:
          - http-server
        ports:
        - containerPort: 8888
